Fixed TASK-823
TaskarCenterAtUW/TDEI-python-ms-osw-confidence-metric pull request #6
Opened 2024-01-22 11:57 UTC by sujata-m

Fixed [Task-823](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/823/)

2024-01-25 04:33 UTC, susrisha requested changes
Some changes needed in documenting and renaming stuff.

2024-01-25 04:33 UTC, susrisha commented on src/config.py
> +    username: str = os.environ.get('USERNAME', 'dev@gaussiansolutions.com')
Please remove default credentials. we will be giving out our credentials here.

2024-01-25 04:33 UTC, susrisha commented on src/service/osw_confidence_metric.py
> +        print("--- %s seconds ---" % (time.time() - start_time))
please use logger here.

2024-01-25 04:33 UTC, susrisha commented on src/service/osw_confidence_metric.py
> +class OSWConfidenceMetric:
Write a couple of lines about what this class does in sequence

2024-01-25 04:33 UTC, susrisha commented on src/service/osw_confidence_service.py
> +        metric = OSWConfidenceMetric(zip_file=osw_file_local_path)
If the confidence calculation only relies on osw file, comment out the download of meta file. Its an additional performance burden to download that file.

2024-01-25 04:33 UTC, susrisha commented on src/service/test.py
> +class DifferentClass:
Rename to `OSWConfidenceMetricTestClass`

2024-01-25 04:33 UTC, susrisha commented on src/service/test.py
> +    def my_function(self):
rename function to `test_osw_confidence_metric_calculation`

2024-01-29 04:53 UTC, susrisha submitted a review, later dismissed

2024-01-29 21:18 UTC, sureshgaussian requested changes

2024-01-29 21:18 UTC, sureshgaussian commented on src/config.py
> +    username: str = os.environ.get('USERNAME', 'dev@gaussiansolutions.com')
Please remove the default credentials from here. Never expose passwords in the code. If the USERNAME/PASSWORD are not provided, just exit the code saying those two are mandatory.

2024-01-29 21:18 UTC, sureshgaussian commented on src/service/test.py
what is this file? why is a test under src folder? If we release this file on public git, we should not have names like DifferentClass. Fix this.

2024-01-29 21:18 UTC, sureshgaussian commented on src/service/osw_confidence_service.py
>                  confidence_library_version='v1.0',
this should be the version of the osw_confidence_metrics library we are using; not a static number. As the code stands today I believe this should be `python_confidence_metric.__version__`
I see the python module for the confidence metrics library is named osw_confidence_metric (from requirements.txt), however the usage of the library is python_confidence_metric. This is not good. Module name and its usuage should be same. Change python_confidence_metric to osw_confidence_metric.

2024-01-30 17:01 UTC, susrisha submitted a review, later dismissed

2024-01-30 17:15 UTC, susrisha approved these changes, later dismissed

2024-01-31 10:24 UTC, susrisha approved these changes

2024-01-31 16:50 UTC, sureshgaussian approved these changes
approved after code review.

2024-02-01 04:20 UTC, merged